<?php

namespace PlayList\Dao;
require(dirname(__FILE__).'/../../config.inc.php');
require(dirname(__FILE__).'/../../dao/TrackStore.php');

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-10-27 at 09:21:53.
 */
class TrackStoreTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var TrackStore
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new TrackStore;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    private function buildFakeObject(){
        $track = new \PlayList\Model\Track();
        $track->setTitle('kikou track');
        $track->setAuthor('zozo des troupaillons');
        $track->setDuration(125);

        return $track;
    }

    /**
     * @covers PlayList\Dao\TrackStore::save
     */
    public function testSave() {
        // Remove the following lines when you implement this test.
        $track = $this->buildFakeObject();
        $result = $this->object->save($track);
        
        $this->assertGreaterThan(-1,$result);
        
    }

    /**
     * @covers PlayList\Dao\TrackStore::getTracks
     * @todo   Implement testGetTracks().
     */
    public function testDelete() {
        $track = $this->buildFakeObject();
        $id = $this->object->save($track);

        $result = $this->object->delete($id);
        
        $this->assertEquals(true,$result);
    }

}
