<?php

namespace PlayList\Dao;
require('../config.inc.php');
require('../dao/TrackStore.php');

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-10-27 at 09:21:53.
 */
class TrackStoreTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var TrackStore
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new TrackStore;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers PlayList\Dao\TrackStore::save
     */
    public function testSave() {
        // Remove the following lines when you implement this test.
        $track = new \PlayList\Model\Track();
        $track->setTitle('kikou track');
        $track->setAuthor('zozo des troupaillons');
        $track->setDuration(125);
        $result = $this->object->save($track);
        
        $this->assertEquals(true,$result);
        
    }

    /**
     * @covers PlayList\Dao\TrackStore::getTracks
     * @todo   Implement testGetTracks().
     */
    public function testGetTracks() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
